library("readxl")
df=read_excel("D:\\Uzma-Documents\\Project 1\\final_clean_PT(61-89).xlsx",sheet=1)
pettitt.test(df$Annual)
snh.test(df$Annual)
bu.test(df$Annual)
sens.slope(df$Annual,conf.level = 0.95)
sens.slope(df$jas,conf.level = 0.95)
sens.slope(df$ON,conf.level = 0.95)
sens.slope(df$AMJ,conf.level = 0.95)
sens.slope(df$Winter,conf.level = 0.95)